//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.5.96
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "24b0950074a6fc2f")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.2")]

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1046 with alias "BasePage"
	/// <summary>Base Page</summary>
	public partial interface IBasePage : IPublishedContent
	{
		/// <summary>Canonical</summary>
		IPublishedContent Canonical { get; }

		/// <summary>Header Page Title</summary>
		string HeaderPageTitle { get; }

		/// <summary>Hide Children</summary>
		bool HideChildren { get; }

		/// <summary>Meta Description</summary>
		string MetaDescription { get; }

		/// <summary>Meta Keywords</summary>
		string MetaKeywords { get; }

		/// <summary>No Follow</summary>
		bool NoFollow { get; }

		/// <summary>No Index</summary>
		bool NoIndex { get; }

		/// <summary>Old Url</summary>
		string OldUrl { get; }

		/// <summary>Page Script</summary>
		string PageScript { get; }

		/// <summary>Title</summary>
		string PageTitle { get; }

		/// <summary>Hide in Navigation</summary>
		bool UmbracoNaviHide { get; }

		/// <summary>Umbraco Redirect</summary>
		IPublishedContent UmbracoRedirect { get; }

		/// <summary>Umbraco URL Alias</summary>
		string UmbracoUrlAlias { get; }

		/// <summary>Umbraco URL Name</summary>
		string UmbracoUrlName { get; }
	}

	/// <summary>Base Page</summary>
	[PublishedContentModel("BasePage")]
	public partial class BasePage : PublishedContentModel, IBasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "BasePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BasePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BasePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Canonical
		///</summary>
		[ImplementPropertyType("canonical")]
		public IPublishedContent Canonical
		{
			get { return GetCanonical(this); }
		}

		/// <summary>Static getter for Canonical</summary>
		public static IPublishedContent GetCanonical(IBasePage that) { return that.GetPropertyValue<IPublishedContent>("canonical"); }

		///<summary>
		/// Header Page Title: The title of document. When left empty, node's name will be used.
		///</summary>
		[ImplementPropertyType("headerPageTitle")]
		public string HeaderPageTitle
		{
			get { return GetHeaderPageTitle(this); }
		}

		/// <summary>Static getter for Header Page Title</summary>
		public static string GetHeaderPageTitle(IBasePage that) { return that.GetPropertyValue<string>("headerPageTitle"); }

		///<summary>
		/// Hide Children
		///</summary>
		[ImplementPropertyType("hideChildren")]
		public bool HideChildren
		{
			get { return GetHideChildren(this); }
		}

		/// <summary>Static getter for Hide Children</summary>
		public static bool GetHideChildren(IBasePage that) { return that.GetPropertyValue<bool>("hideChildren"); }

		///<summary>
		/// Meta Description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return GetMetaDescription(this); }
		}

		/// <summary>Static getter for Meta Description</summary>
		public static string GetMetaDescription(IBasePage that) { return that.GetPropertyValue<string>("metaDescription"); }

		///<summary>
		/// Meta Keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return GetMetaKeywords(this); }
		}

		/// <summary>Static getter for Meta Keywords</summary>
		public static string GetMetaKeywords(IBasePage that) { return that.GetPropertyValue<string>("metaKeywords"); }

		///<summary>
		/// No Follow
		///</summary>
		[ImplementPropertyType("noFollow")]
		public bool NoFollow
		{
			get { return GetNoFollow(this); }
		}

		/// <summary>Static getter for No Follow</summary>
		public static bool GetNoFollow(IBasePage that) { return that.GetPropertyValue<bool>("noFollow"); }

		///<summary>
		/// No Index
		///</summary>
		[ImplementPropertyType("noIndex")]
		public bool NoIndex
		{
			get { return GetNoIndex(this); }
		}

		/// <summary>Static getter for No Index</summary>
		public static bool GetNoIndex(IBasePage that) { return that.GetPropertyValue<bool>("noIndex"); }

		///<summary>
		/// Old Url
		///</summary>
		[ImplementPropertyType("oldUrl")]
		public string OldUrl
		{
			get { return GetOldUrl(this); }
		}

		/// <summary>Static getter for Old Url</summary>
		public static string GetOldUrl(IBasePage that) { return that.GetPropertyValue<string>("oldUrl"); }

		///<summary>
		/// Page Script: Script on this page
		///</summary>
		[ImplementPropertyType("pageScript")]
		public string PageScript
		{
			get { return GetPageScript(this); }
		}

		/// <summary>Static getter for Page Script</summary>
		public static string GetPageScript(IBasePage that) { return that.GetPropertyValue<string>("pageScript"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return GetPageTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetPageTitle(IBasePage that) { return that.GetPropertyValue<string>("pageTitle"); }

		///<summary>
		/// Hide in Navigation: Use this property if you wish to hide this page in the navigation.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return GetUmbracoNaviHide(this); }
		}

		/// <summary>Static getter for Hide in Navigation</summary>
		public static bool GetUmbracoNaviHide(IBasePage that) { return that.GetPropertyValue<bool>("umbracoNaviHide"); }

		///<summary>
		/// Umbraco Redirect: Pick a node you wish to redirect to if the user lands on this node.
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public IPublishedContent UmbracoRedirect
		{
			get { return GetUmbracoRedirect(this); }
		}

		/// <summary>Static getter for Umbraco Redirect</summary>
		public static IPublishedContent GetUmbracoRedirect(IBasePage that) { return that.GetPropertyValue<IPublishedContent>("umbracoRedirect"); }

		///<summary>
		/// Umbraco URL Alias: Use this to give a node multiple urls.eg: home,homepage/another-level
		///</summary>
		[ImplementPropertyType("umbracoUrlAlias")]
		public string UmbracoUrlAlias
		{
			get { return GetUmbracoUrlAlias(this); }
		}

		/// <summary>Static getter for Umbraco URL Alias</summary>
		public static string GetUmbracoUrlAlias(IBasePage that) { return that.GetPropertyValue<string>("umbracoUrlAlias"); }

		///<summary>
		/// Umbraco URL Name: If you wish to change the URL of the node without changing the node name fill this in.eg: warren
		///</summary>
		[ImplementPropertyType("umbracoUrlName")]
		public string UmbracoUrlName
		{
			get { return GetUmbracoUrlName(this); }
		}

		/// <summary>Static getter for Umbraco URL Name</summary>
		public static string GetUmbracoUrlName(IBasePage that) { return that.GetPropertyValue<string>("umbracoUrlName"); }
	}

	/// <summary>HomePage</summary>
	[PublishedContentModel("homePage")]
	public partial class HomePage : PublishedContentModel, IBasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Site Script: Script on all pages
		///</summary>
		[ImplementPropertyType("siteScript")]
		public string SiteScript
		{
			get { return this.GetPropertyValue<string>("siteScript"); }
		}

		///<summary>
		/// Canonical
		///</summary>
		[ImplementPropertyType("canonical")]
		public IPublishedContent Canonical
		{
			get { return BasePage.GetCanonical(this); }
		}

		///<summary>
		/// Header Page Title: The title of document. When left empty, node's name will be used.
		///</summary>
		[ImplementPropertyType("headerPageTitle")]
		public string HeaderPageTitle
		{
			get { return BasePage.GetHeaderPageTitle(this); }
		}

		///<summary>
		/// Hide Children
		///</summary>
		[ImplementPropertyType("hideChildren")]
		public bool HideChildren
		{
			get { return BasePage.GetHideChildren(this); }
		}

		///<summary>
		/// Meta Description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return BasePage.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta Keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return BasePage.GetMetaKeywords(this); }
		}

		///<summary>
		/// No Follow
		///</summary>
		[ImplementPropertyType("noFollow")]
		public bool NoFollow
		{
			get { return BasePage.GetNoFollow(this); }
		}

		///<summary>
		/// No Index
		///</summary>
		[ImplementPropertyType("noIndex")]
		public bool NoIndex
		{
			get { return BasePage.GetNoIndex(this); }
		}

		///<summary>
		/// Old Url
		///</summary>
		[ImplementPropertyType("oldUrl")]
		public string OldUrl
		{
			get { return BasePage.GetOldUrl(this); }
		}

		///<summary>
		/// Page Script: Script on this page
		///</summary>
		[ImplementPropertyType("pageScript")]
		public string PageScript
		{
			get { return BasePage.GetPageScript(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return BasePage.GetPageTitle(this); }
		}

		///<summary>
		/// Hide in Navigation: Use this property if you wish to hide this page in the navigation.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return BasePage.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Umbraco Redirect: Pick a node you wish to redirect to if the user lands on this node.
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public IPublishedContent UmbracoRedirect
		{
			get { return BasePage.GetUmbracoRedirect(this); }
		}

		///<summary>
		/// Umbraco URL Alias: Use this to give a node multiple urls.eg: home,homepage/another-level
		///</summary>
		[ImplementPropertyType("umbracoUrlAlias")]
		public string UmbracoUrlAlias
		{
			get { return BasePage.GetUmbracoUrlAlias(this); }
		}

		///<summary>
		/// Umbraco URL Name: If you wish to change the URL of the node without changing the node name fill this in.eg: warren
		///</summary>
		[ImplementPropertyType("umbracoUrlName")]
		public string UmbracoUrlName
		{
			get { return BasePage.GetUmbracoUrlName(this); }
		}
	}

	/// <summary>Content Page</summary>
	[PublishedContentModel("contentPage")]
	public partial class ContentPage : PublishedContentModel, IBasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contentPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContentPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContentPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Canonical
		///</summary>
		[ImplementPropertyType("canonical")]
		public IPublishedContent Canonical
		{
			get { return BasePage.GetCanonical(this); }
		}

		///<summary>
		/// Header Page Title: The title of document. When left empty, node's name will be used.
		///</summary>
		[ImplementPropertyType("headerPageTitle")]
		public string HeaderPageTitle
		{
			get { return BasePage.GetHeaderPageTitle(this); }
		}

		///<summary>
		/// Hide Children
		///</summary>
		[ImplementPropertyType("hideChildren")]
		public bool HideChildren
		{
			get { return BasePage.GetHideChildren(this); }
		}

		///<summary>
		/// Meta Description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return BasePage.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta Keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return BasePage.GetMetaKeywords(this); }
		}

		///<summary>
		/// No Follow
		///</summary>
		[ImplementPropertyType("noFollow")]
		public bool NoFollow
		{
			get { return BasePage.GetNoFollow(this); }
		}

		///<summary>
		/// No Index
		///</summary>
		[ImplementPropertyType("noIndex")]
		public bool NoIndex
		{
			get { return BasePage.GetNoIndex(this); }
		}

		///<summary>
		/// Old Url
		///</summary>
		[ImplementPropertyType("oldUrl")]
		public string OldUrl
		{
			get { return BasePage.GetOldUrl(this); }
		}

		///<summary>
		/// Page Script: Script on this page
		///</summary>
		[ImplementPropertyType("pageScript")]
		public string PageScript
		{
			get { return BasePage.GetPageScript(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return BasePage.GetPageTitle(this); }
		}

		///<summary>
		/// Hide in Navigation: Use this property if you wish to hide this page in the navigation.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return BasePage.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Umbraco Redirect: Pick a node you wish to redirect to if the user lands on this node.
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public IPublishedContent UmbracoRedirect
		{
			get { return BasePage.GetUmbracoRedirect(this); }
		}

		///<summary>
		/// Umbraco URL Alias: Use this to give a node multiple urls.eg: home,homepage/another-level
		///</summary>
		[ImplementPropertyType("umbracoUrlAlias")]
		public string UmbracoUrlAlias
		{
			get { return BasePage.GetUmbracoUrlAlias(this); }
		}

		///<summary>
		/// Umbraco URL Name: If you wish to change the URL of the node without changing the node name fill this in.eg: warren
		///</summary>
		[ImplementPropertyType("umbracoUrlName")]
		public string UmbracoUrlName
		{
			get { return BasePage.GetUmbracoUrlName(this); }
		}
	}

	/// <summary>Page Not Found</summary>
	[PublishedContentModel("pageNotFound")]
	public partial class PageNotFound : PublishedContentModel, IBasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pageNotFound";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PageNotFound(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PageNotFound, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Canonical
		///</summary>
		[ImplementPropertyType("canonical")]
		public IPublishedContent Canonical
		{
			get { return BasePage.GetCanonical(this); }
		}

		///<summary>
		/// Header Page Title: The title of document. When left empty, node's name will be used.
		///</summary>
		[ImplementPropertyType("headerPageTitle")]
		public string HeaderPageTitle
		{
			get { return BasePage.GetHeaderPageTitle(this); }
		}

		///<summary>
		/// Hide Children
		///</summary>
		[ImplementPropertyType("hideChildren")]
		public bool HideChildren
		{
			get { return BasePage.GetHideChildren(this); }
		}

		///<summary>
		/// Meta Description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return BasePage.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta Keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return BasePage.GetMetaKeywords(this); }
		}

		///<summary>
		/// No Follow
		///</summary>
		[ImplementPropertyType("noFollow")]
		public bool NoFollow
		{
			get { return BasePage.GetNoFollow(this); }
		}

		///<summary>
		/// No Index
		///</summary>
		[ImplementPropertyType("noIndex")]
		public bool NoIndex
		{
			get { return BasePage.GetNoIndex(this); }
		}

		///<summary>
		/// Old Url
		///</summary>
		[ImplementPropertyType("oldUrl")]
		public string OldUrl
		{
			get { return BasePage.GetOldUrl(this); }
		}

		///<summary>
		/// Page Script: Script on this page
		///</summary>
		[ImplementPropertyType("pageScript")]
		public string PageScript
		{
			get { return BasePage.GetPageScript(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return BasePage.GetPageTitle(this); }
		}

		///<summary>
		/// Hide in Navigation: Use this property if you wish to hide this page in the navigation.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return BasePage.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Umbraco Redirect: Pick a node you wish to redirect to if the user lands on this node.
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public IPublishedContent UmbracoRedirect
		{
			get { return BasePage.GetUmbracoRedirect(this); }
		}

		///<summary>
		/// Umbraco URL Alias: Use this to give a node multiple urls.eg: home,homepage/another-level
		///</summary>
		[ImplementPropertyType("umbracoUrlAlias")]
		public string UmbracoUrlAlias
		{
			get { return BasePage.GetUmbracoUrlAlias(this); }
		}

		///<summary>
		/// Umbraco URL Name: If you wish to change the URL of the node without changing the node name fill this in.eg: warren
		///</summary>
		[ImplementPropertyType("umbracoUrlName")]
		public string UmbracoUrlName
		{
			get { return BasePage.GetUmbracoUrlName(this); }
		}
	}

	/// <summary>Search</summary>
	[PublishedContentModel("search")]
	public partial class Search : PublishedContentModel, IBasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "search";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Search(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Search, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Canonical
		///</summary>
		[ImplementPropertyType("canonical")]
		public IPublishedContent Canonical
		{
			get { return BasePage.GetCanonical(this); }
		}

		///<summary>
		/// Header Page Title: The title of document. When left empty, node's name will be used.
		///</summary>
		[ImplementPropertyType("headerPageTitle")]
		public string HeaderPageTitle
		{
			get { return BasePage.GetHeaderPageTitle(this); }
		}

		///<summary>
		/// Hide Children
		///</summary>
		[ImplementPropertyType("hideChildren")]
		public bool HideChildren
		{
			get { return BasePage.GetHideChildren(this); }
		}

		///<summary>
		/// Meta Description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return BasePage.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta Keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return BasePage.GetMetaKeywords(this); }
		}

		///<summary>
		/// No Follow
		///</summary>
		[ImplementPropertyType("noFollow")]
		public bool NoFollow
		{
			get { return BasePage.GetNoFollow(this); }
		}

		///<summary>
		/// No Index
		///</summary>
		[ImplementPropertyType("noIndex")]
		public bool NoIndex
		{
			get { return BasePage.GetNoIndex(this); }
		}

		///<summary>
		/// Old Url
		///</summary>
		[ImplementPropertyType("oldUrl")]
		public string OldUrl
		{
			get { return BasePage.GetOldUrl(this); }
		}

		///<summary>
		/// Page Script: Script on this page
		///</summary>
		[ImplementPropertyType("pageScript")]
		public string PageScript
		{
			get { return BasePage.GetPageScript(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return BasePage.GetPageTitle(this); }
		}

		///<summary>
		/// Hide in Navigation: Use this property if you wish to hide this page in the navigation.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return BasePage.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Umbraco Redirect: Pick a node you wish to redirect to if the user lands on this node.
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public IPublishedContent UmbracoRedirect
		{
			get { return BasePage.GetUmbracoRedirect(this); }
		}

		///<summary>
		/// Umbraco URL Alias: Use this to give a node multiple urls.eg: home,homepage/another-level
		///</summary>
		[ImplementPropertyType("umbracoUrlAlias")]
		public string UmbracoUrlAlias
		{
			get { return BasePage.GetUmbracoUrlAlias(this); }
		}

		///<summary>
		/// Umbraco URL Name: If you wish to change the URL of the node without changing the node name fill this in.eg: warren
		///</summary>
		[ImplementPropertyType("umbracoUrlName")]
		public string UmbracoUrlName
		{
			get { return BasePage.GetUmbracoUrlName(this); }
		}
	}

	/// <summary>Category Overview</summary>
	[PublishedContentModel("categoryOverview")]
	public partial class CategoryOverview : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "categoryOverview";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CategoryOverview(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CategoryOverview, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Category</summary>
	[PublishedContentModel("category")]
	public partial class Category : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "category";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Category(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Category, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Category Tags
		///</summary>
		[ImplementPropertyType("categoryTags")]
		public IEnumerable<IPublishedContent> CategoryTags
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("categoryTags"); }
		}
	}

	/// <summary>Products Overview</summary>
	[PublishedContentModel("productsOverview")]
	public partial class ProductsOverview : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "productsOverview";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProductsOverview(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProductsOverview, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Product</summary>
	[PublishedContentModel("product")]
	public partial class Product : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "product";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Product(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Product, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Nop Id
		///</summary>
		[ImplementPropertyType("nopId")]
		public string NopId
		{
			get { return this.GetPropertyValue<string>("nopId"); }
		}

		///<summary>
		/// Product Image
		///</summary>
		[ImplementPropertyType("productImage")]
		public IPublishedContent ProductImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("productImage"); }
		}

		///<summary>
		/// Tags
		///</summary>
		[ImplementPropertyType("tags")]
		public IEnumerable<IPublishedContent> Tags
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("tags"); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}
